### ISSUE TITLE
Audios not being cut properly

### ISSUE THREAD

**Issue by striquer** [cevadtokatli/mp3-cutter#1]
I searched into the code but i wasn't able to find why this is happening, but all audios that i try to cut end up being wrong. Every time it cutes about 2s more then it's supposed to do, or even if i don't wanna cut anything, it cutes about 2s too.

**Comment by cevadtokatli** [comment]
I didn't get any problem like that while testing, but in any case I've made a few changes in the part of the code where the problem can be. If you're still having trouble in cutting files, please email me an example file you couldn't cut.

**Comment by striquer** [comment]
I'm still having the same problem, really weird. I will explain to you my flow, maybe you can figure it out if i do that. The user records a voice over audio on browser and sends it to my node application, then i grab the base64 that frontend is sending, create a file with file system and buffer then i send this file to your lib and a empty file as well. But when i'm not trying to cut anything it return to me a -2second audio, and when i try to cut it return a -1 s or 2 s file as well. I'll send you the file i'm trying to cut with the start and end information that i'm trying to use. Thanks for replying so fast.

**Comment by striquer** [comment]
I found out that the audios wasn't real MP3, just their extensions were set to MP3, but they were encoded to WAV inside them. That's why it wasn't working, thanks for your time! Great lib.
