### ISSUE TITLE
Does it re-encode ?

### ISSUE THREAD

**Issue by Xample** [cevadtokatli/mp3-cutter#3]
Does it re-encode the mp3 (with potential loss of quality) or it simply clips the current data ?

**Comment by FadyQJ** [comment]
Hey,

Just in case someone else stumbles upon this, I too was looking for an mp3 cutter that does not re-encode.

Based on the code written in:
https://github.com/cevadtokatli/mp3-cutter/blob/master/lib/cutter.js
It seems to cut the file as is without re-encoding.
It is using an fs stream to read the file and write the result while cutting the specified part, so, it is just copying the file without any audio manipulation.

**Comment by cevadtokatli** [comment]
no, it doesn't re-encode
